language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adithyasekar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adithyasekar/react-test npm run test -- --coverage

after_success:
  - docker build -t adithyasekar/multi-client ./client
  - docker build -t adithyasekar/multi-nginx ./nginx
  - docker build -t adithyasekar/multi-server ./server
  - docker build -t adithyasekar/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to Docker Hub
  - docker push adithyasekar/multi-client
  - docker push adithyasekar/multi-nginx
  - docker push adithyasekar/multi-server
  - docker push adithyasekar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-378344169585"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
